import { Inter, Euphoria_Script, Exo } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

// const inter = Inter({ subsets: ["latin"] });
const euphoria = Euphoria_Script({
  subsets: ["latin"],
  display: "swap",
  weight: "400"
})
const exo = Exo({
  subsets: ["latin"],
  display: "swap"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Euphoria+Script&display=swap" rel="stylesheet"/>

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Epilogue:ital,wght@0,100..900;1,100..900&family=Exo:ital,wght@0,100..900;1,100..900&family=Fanwood+Text:ital@0;1&display=swap" rel="stylesheet"></link>

      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// export default function Layout({children}) {
//   return(
//     <>
//       <main className={`${euphoria.className} `}>{children}</main>
//       <Footer></Footer>
//     </>
//   )
// }
